from enum import StrEnum


class CaseStatus(StrEnum):
    CREATED = "CREATED"
    IN_PROGRESS = "IN_PROGRESS"
    PCP_ORDER_PENDING = "PCP_ORDER_PENDING"
    ORDER_VALIDATED = "ORDER_VALIDATED"
    SUPPLIER_SEARCH = "SUPPLIER_SEARCH"
    SUPPLIER_QUALIFIED = "SUPPLIER_QUALIFIED"
    READY_TO_MATCH = "READY_TO_MATCH"
    DELIVERY_COMMITTED = "DELIVERY_COMMITTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    COMPLETE = "COMPLETE"
    ESCALATED = "ESCALATED"


class SupplierCandidateStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    NO_ANSWER = "NO_ANSWER"
    NOT_ACCEPTING_NEW_PATIENTS = "NOT_ACCEPTING_NEW_PATIENTS"
    DOES_NOT_PROVIDE_K0001 = "DOES_NOT_PROVIDE_K0001"
    K0001_OUT_OF_STOCK = "K0001_OUT_OF_STOCK"
    DOES_NOT_ACCEPT_ASSIGNMENT = "DOES_NOT_ACCEPT_ASSIGNMENT"
    QUALIFIED = "QUALIFIED"
    FAILED = "FAILED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"


class EscalationReason(StrEnum):
    PCP_UNRESPONSIVE = "PCP_UNRESPONSIVE"
    NO_SUPPLIER_AVAILABLE = "NO_SUPPLIER_AVAILABLE"
    SUPPLIER_COMMITMENT_BROKEN = "SUPPLIER_COMMITMENT_BROKEN"
    PATIENT_NOT_ELIGIBLE = "PATIENT_NOT_ELIGIBLE"
    ORDER_INVALID = "ORDER_INVALID"
    ASSIGNMENT_CONSENT_REQUIRED = "ASSIGNMENT_CONSENT_REQUIRED"
    ASSIGNMENT_CONSENT_DECLINED = "ASSIGNMENT_CONSENT_DECLINED"


class EventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    PCP_CONTACT_ATTEMPTED = "PCP_CONTACT_ATTEMPTED"
    PCP_RESPONSE_RECEIVED = "PCP_RESPONSE_RECEIVED"
    ORDER_VALIDATED = "ORDER_VALIDATED"
    ORDER_VALIDATION_FAILED = "ORDER_VALIDATION_FAILED"
    SUPPLIER_CONTACT_ATTEMPTED = "SUPPLIER_CONTACT_ATTEMPTED"
    SUPPLIER_RESPONSE_RECEIVED = "SUPPLIER_RESPONSE_RECEIVED"
    SUPPLIER_QUALIFIED = "SUPPLIER_QUALIFIED"
    SUPPLIER_REJECTED = "SUPPLIER_REJECTED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    DELIVERY_COMMITTED = "DELIVERY_COMMITTED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    COMMITMENT_STALLED = "COMMITMENT_STALLED"
    PATIENT_NOTIFIED = "PATIENT_NOTIFIED"
    PATIENT_RESPONSE_RECEIVED = "PATIENT_RESPONSE_RECEIVED"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    CASE_COMPLETED = "CASE_COMPLETED"
